<div class="alert alert-success">
	<h2>HISTORIA</h2>
</div>
<div style="text-align: justify; font-size: 15px; text-indent: 2em;">
<img src="<?php print path("www/lib/images/historia.png","www") ?>" style="float: left; margin-right: 20px;" />
<p>La profesión de enfermería ha enfrentado a través de su existencia múltiples situaciones exclusivas de la disciplina, entre las que destaca la definición de su identidad profesional, una aparente debilidad gremial y una sentida subvaloración histórica; sin embargo, el mayor impacto se ha observado en su formación académica, ya que tradicionalmente y por reflejo del contexto socioeconómico, político y cultural, el nivel educativo al que se podía acceder tenía menos años de escolaridad respecto a otros profesionales de la salud.</p>

<p>A mediados del año 1800, se inicia en México la educación escolarizada de la enfermera bajo una perspectiva eminentemente médica, cuyo principal objetivo fue satisfacer las necesidades de un número importante de hospitales públicos y privados, que requerían personal capacitado y que cumpliera las órdenes médicas al cuidar de los enfermos. Fue el gremio médico quien decidió los conocimientos y destrezas que debía tener el profesional de enfermería; en el perfil del egresado resaltaba el hacer y actitudes de subordinación, características que correspondían “al ayudante del médico”.</p>

<p>A partir de la década de 1970 en que iniciaban los primeros programas de licenciatura en enfermería, se han realizado grandes esfuerzos y elaborado propuestas para diferenciar este nivel del técnico y ubicarlo en el el mismo status de otras carreras universitarias; no obstante, la situación que a la fecha subsiste sigue siendo la falta de diferenciación en la formación de la enfermera técnica y la licenciada. Aunado a esto se han generado otros niveles más, que han creado confusión y superposición o traslape de funciones entre uno y otro.</p>

<p>El status profesional está ligado a la escolaridad, de manera que ún y cuando se logren altos niveles de excelencia en la formación en enfermería, no será considerado en igualdad con otros profesionales mientras no se establezcan con claridad los niveles de preparación.</p>

<p>En 1984 esta situación fue llevada ante la Comisión Interinstitucional para la Formación de Recursos Humanos para la Salud (CIFRHS), la cual a través del Comité de Enseñanza de Pre Grado y Servicio Social, convocó a un grupo ad hoc, integrado por expertos de enfermería, quienes se dieron a la tarea de revisar ampliamente la situación a fin de establecer la regulación para la apertura y funcionamiento de las Escuelas de Enfermería, así como el ingreso de estudiantes a las mismas a través de Normas Básicas de Enseñanza de Enfermería, mismas que fueron presentadas en 1987 a la H. Comisión Interinstitucional y aprobadas por la misma el 8 de julio de 1988 con carácter de recomendaciones, de tal suerte que cada institución educativa las adoptó en forma autónoma.</p>

<p>El Colegio Nacional de Enfermeras, como miembro del Consejo Internacional de Enfermeras (CIE), se unió al proyecto de reglamentación mundial de enfermeras (1988-1994) y a partir de la identificación de necesidades de enfermería en México coordinó un proyecto paralelo denominado “Reglamento de Enfermería en Materia de la Formación y el Ejercicio Profesional en México”, propuesta que se sometió a consideración de las Cámaras del Congreso de la Unión y que aún esta pendiente el dictamen correspondiente.</p>
<p>La escuela de Enfermería de Apatzingán, A.C. Abrió sus puertas por primera vez, el 5 de septiembre de 1976 bajo la dirección del Dr. Rafael flores Pérez., con una planta de profesores de 5 médicos y 2 enfermeras, una secretaria, un intendente y una supervisora.</p>

<p>En cuanto a cooperaciones escolares los 55 estudiantes que iniciaron pagaron una cuota de $30.00 para sufragar parte de los gastos administrativos. La tesorera que inicio fue la Sra. Carmen Álvarez de sosa. La visión del Dr. Flores fue formar enfermeras profesionistas que satisficieran las carencias que había en toda la región, había muchas necesidades que cubrir, por lo mismo los profesores impartían sus clases voluntariamente cooperando así con la causa filantrópica.</p>

<p>La escuela inicio anexa al hospital general “Ramón Ponce Álvarez.” egreso así la primera generación de 36 alumnas el 18 de julio de 1979. Estas egresadas fueron a dar su servicio social a diferentes partes de la república de estas el 78% se han titulado. Había muchos comentarios negativos acerca de la escuela, pero se recibió de la dirección general de profesores del departamento de instituciones educativa y expediente 16-000534, que en el artículo 3°., certificación del acta n° 14 de la sesión del h. consejo celebrada el día 13 de enero de 1978, signada por el Ing. José Fco. Ruiz vega., secretario general de la universidad michoacana, hizo constar que la escuela de enfermería de Apatzingán se encuentra incorporada a la universidad citada (tomo i foja 07). Esto se informo a los padres de familia y a la población en general a través de la radio y la prensa. </p>
<p>El terreno de la escuela es una donación del hospital citado. Comenzó con 3 aulas un laboratorio, una oficina y un extenso patio con árboles frutales y de ornato y baños para hombres y mujeres. </p>
<p>A partir de 1982 a los profesores se les empezó a pagar cuotas simbólicas. Se continuo creciendo con el mismo entusiasmo y la misma visión. Generación tras generación en un 80% trabajando en la entidad, otros estados y en el extranjero. han egresado un promedio de 900 estudiantes a estas fechas, la escuela cuenta con una dirección actualizada completamente, equipada: con 3 computadoras fax, impresora, internet, un espacio pequeño para los profesores, 3 archiveros, 4 escritorios, recibidor con 4 sillas, tenemos también la biblioteca con volúmenes, relativamente actualizados, con 6 computadoras una fotocopiadora(prestada) aire acondicionado 2 mesas sillas para hacer trabajos de investigación, y hay una persona responsable de esta unidad. También una lonchera accesible para que los estudiantes puedan degustar los alimentos con toda la higiene requerida. Contamos con un laboratorio para las practicas clínicas hospitalarias, baño para profesores, baño para estudiantes,  contamos con 2 baños para mujeres, uno con 2 retretes y otro con 4 y el baño de hombres con retrete y mingitorio, hay un jardinero que se encarga del mantenimiento de las áreas verdes un intendente, para la limpieza y mensajería, la misión es participar en todas las áreas de la salud con eficacia y calidad.</p>
<p>&nbsp;</p>
</div>